# Generated by Django 4.2.7 on 2023-11-20 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_event_name_event_name_remove_event_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventDetail',
            new_name='Occurence',
        ),
    ]
