# Generated by Django 4.2.7 on 2023-11-20 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_eventdetail_occurence'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Occurence',
            new_name='Occurrence',
        ),
    ]
