# Generated by Django 4.2.7 on 2023-11-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_occurrence_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='emoji',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
