# Generated by Django 4.2.7 on 2023-11-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_emoji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='emoji',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
