# Generated by Django 4.2.7 on 2023-11-20 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_emoji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='emoji',
            field=models.CharField(max_length=42, null=True),
        ),
    ]
