# Generated by Django 4.2.7 on 2023-11-22 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
