# Generated by Django 4.2.7 on 2023-12-13 04:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='timeofday',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
