# Generated by Django 4.2.7 on 2023-12-13 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='note',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
