# Generated by Django 4.2.7 on 2024-02-09 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_occurrence_note'),
        ('events', '0014_alter_occurrence_timeofday'),
    ]

    operations = [
    ]
