version: '3.8'

services:
  db:
    platform: linux/amd64
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
    volumes:
      -  postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    platform: linux/amd64
    build:
      context: .
      args:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_HOST: ${POSTGRES_HOST}
    volumes:
      - .:/app
    expose:
      - "8888" 
    environment:
      - DEBUG=1
  nginx:
    platform: linux/amd64
    image: nginx:latest 
    user: "root"
    ports:
      - "80:80"
      - "443:443"  # Map port 80 on the host to port 80 in the Nginx container
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /Users/nicoledavenport/maya/events/static:/Users/nicoledavenport/maya/events/static
      - /etc/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - web
volumes:
    postgres_data: